/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_rt_sg_racsystemtest_serial_SerialPort
#define _Included_rt_sg_racsystemtest_serial_SerialPort
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jobject JNICALL Java_rt_sg_racsystemtest_serial_SerialPort_open
  (JNIEnv *, jclass, jstring, jint, jint);


JNIEXPORT void JNICALL Java_rt_sg_racsystemtest_serial_SerialPort_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
